# Generated by Django 4.2.14 on 2024-07-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rateing',
            field=models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad'), ('Average', 'Average')], default='Average', max_length=100),
        ),
    ]
