# Generated by Django 4.2.14 on 2024-07-14 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50, verbose_name='Category Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity Available')),
                ('desc', models.TextField(max_length=200, verbose_name='Description')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('published_date', models.DateField(default=None, null=True, verbose_name='Published Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_master.category', verbose_name='Category')),
            ],
        ),
    ]
